from django.contrib import admin
from .models import *
admin.site.register(MainSliderImages)
admin.site.register(About)
admin.site.register(Partiners)
admin.site.register(UserPatient)
admin.site.register(LoginPatient)
admin.site.register(UserSpecialist)
# admin.site.register(SpecialistLogin)
# admin.site.register(Specialization)
admin.site.register(Ambulance)
# admin.site.register(AppointmentTypes)
admin.site.register(Ambulance_Orders)
admin.site.register(Appointment)
# admin.site.register(PatientAppointments)
# admin.site.register(PatientMessages)
# admin.site.register(SpecialistMessages)
# admin.site.register(Driver)
admin.site.register(HomeCare)
admin.site.register(HomeCareServices)
