# Generated by Django 3.1.13 on 2021-10-11 18:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='ambulances/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('iso3', models.CharField(max_length=10)),
                ('numeric_code', models.CharField(max_length=10)),
                ('iso2', models.CharField(max_length=5)),
                ('phonecode', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('tld', models.CharField(blank=True, max_length=255, null=True)),
                ('native', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(max_length=255)),
                ('subregion', models.CharField(max_length=255)),
                ('timezones', models.TextField()),
                ('translations', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=19)),
                ('emoji', models.CharField(max_length=200)),
                ('emojiU', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.SmallIntegerField(default=1)),
                ('wikiDataId', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainSliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mainslider/')),
            ],
        ),
        migrations.CreateModel(
            name='Partiners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='ourpartiners/')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Dr', 'Doctor'), ('Sergion', 'Sergion'), ('Dentist', 'Dentist'), ('Nurse', 'Nurse'), ('Councillor', 'Councillor')], max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='userpatients/')),
            ],
        ),
        migrations.CreateModel(
            name='UserSpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='userspecialists/')),
                ('about', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=True)),
                ('specialization', models.ManyToManyField(to='doctoronlinemaster.Specialization')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userspecialist')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('userSpecialist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userspecialist')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userpatient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfAppointment', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userpatient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userspecialist')),
            ],
        ),
        migrations.CreateModel(
            name='LoginPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('userPatient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userpatient')),
            ],
        ),
        migrations.CreateModel(
            name='HomeCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userpatient')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userspecialist')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('typeOfAppointment', models.CharField(max_length=255)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userspecialist')),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.ambulance')),
                ('assigned_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userspecialist')),
                ('userPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userpatient')),
            ],
        ),
    ]
