# Generated by Django 3.1.13 on 2021-10-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctoronlinemaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='type',
            field=models.CharField(choices=[('Dr', 'Doctor'), ('Sergion', 'Sergeon'), ('Dentist', 'Dentist'), ('Nurse', 'Nurse'), ('Councillor', 'Councillor'), ('optician', 'optician')], max_length=255),
        ),
    ]
