# Generated by Django 3.1.13 on 2021-10-25 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doctoronlinemaster', '0019_auto_20211025_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecareservices',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctoronlinemaster.userpatient'),
        ),
        migrations.AlterField(
            model_name='ambulance_orders',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 33, 53, 42953)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 33, 53, 46952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 33, 53, 46952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='homecare',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 19, 33, 53, 43952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='homecare',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 19, 33, 53, 43952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='homecareservices',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 33, 53, 44956)),
        ),
        migrations.AlterField(
            model_name='patientappointments',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 33, 53, 46952)),
        ),
        migrations.AlterField(
            model_name='patientappointments',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 33, 53, 46952)),
        ),
        migrations.AlterField(
            model_name='patientmessages',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 33, 53, 47952)),
        ),
        migrations.AlterField(
            model_name='specialistmessages',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 33, 53, 47952)),
        ),
    ]
